import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`} style={{width:"100%"}}>
        <h1 className="text-center font-bold text-xl md:text-5xl fonts-mono mb-3 p-5">
          Xiangqi-PGN-Converter
        </h1>
        {children}
      </body>
    </html>
  );
}
